package docker

import (
	"fmt"
	"os"
	"strings"

	"github.com/depotly/depotly/pkg/config"
)

// GenerateCompose generates a docker-compose.yml from the config.
func GenerateCompose(cfg *config.Config) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Generated by Depotly for project: %s\n", cfg.Project))
	sb.WriteString("services:\n")

	// PostgreSQL
	if cfg.Services.Postgres.Enabled {
		sb.WriteString(fmt.Sprintf(`  postgres:
    image: %s
    container_name: %s
    ports:
      - "%d:5432"
    environment:
      POSTGRES_DB: %s
      POSTGRES_USER: %s
      POSTGRES_PASSWORD: %s
    volumes:
      - %s:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U %s -d %s"]
      interval: 5s
      timeout: 5s
      retries: 5

`,
			cfg.Services.Postgres.Image,
			cfg.Services.Postgres.ContainerName,
			cfg.Services.Postgres.Port,
			cfg.Services.Postgres.Database,
			cfg.Services.Postgres.User,
			cfg.Services.Postgres.Password,
			cfg.Services.Postgres.Volume,
			cfg.Services.Postgres.User,
			cfg.Services.Postgres.Database,
		))
	}

	// Redis
	if cfg.Services.Redis.Enabled {
		sb.WriteString(fmt.Sprintf(`  redis:
    image: %s
    container_name: %s
    ports:
      - "%d:6379"
    volumes:
      - %s:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

`,
			cfg.Services.Redis.Image,
			cfg.Services.Redis.ContainerName,
			cfg.Services.Redis.Port,
			cfg.Services.Redis.Volume,
		))
	}

	// MinIO / S3-compatible object storage
	if cfg.Services.Object.Enabled {
		sb.WriteString(fmt.Sprintf(`  object:
    image: %s
    container_name: %s
    ports:
      - "%d:9000"
      - "%d:9001"
    environment:
      MINIO_ROOT_USER: %s
      MINIO_ROOT_PASSWORD: %s
    volumes:
      - %s:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

`,
			cfg.Services.Object.Image,
			cfg.Services.Object.ContainerName,
			cfg.Services.Object.Port,
			cfg.Services.Object.ConsolePort,
			cfg.Services.Object.AccessKey,
			cfg.Services.Object.SecretKey,
			cfg.Services.Object.Volume,
		))
	}

	// MongoDB
	if cfg.Services.Mongo.Enabled {
		sb.WriteString(fmt.Sprintf(`  mongo:
    image: %s
    container_name: %s
    ports:
      - "%d:27017"
    volumes:
      - %s:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

`,
			cfg.Services.Mongo.Image,
			cfg.Services.Mongo.ContainerName,
			cfg.Services.Mongo.Port,
			cfg.Services.Mongo.Volume,
		))
	}

	// Shared network
	sb.WriteString("networks:\n  default:\n    name: depotly\n")

	return sb.String(), nil
}

// WriteComposeFile generates and writes the docker-compose file.
func WriteComposeFile(cfg *config.Config, path string) error {
	content, err := GenerateCompose(cfg)
	if err != nil {
		return err
	}

	// Ensure directory exists
	dir := path
	if idx := strings.LastIndex(path, string(os.PathSeparator)); idx >= 0 {
		dir = path[:idx]
	} else if idx := strings.LastIndex(path, "/"); idx >= 0 {
		dir = path[:idx]
	}
	if dir != path {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("creating compose directory: %w", err)
		}
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing compose file: %w", err)
	}

	return nil
}
