package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/depotly/depotly/pkg/config"
	"github.com/depotly/depotly/pkg/utils"
	"github.com/spf13/cobra"
)

var projectName string

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a new Depotly project",
	Long: `Generate depotly.yaml configuration and create the required
directory structure for a new Depotly project.`,
	Run: func(cmd *cobra.Command, args []string) {
		name := projectName
		if name == "" {
			// Use current directory name as project name
			cwd, err := os.Getwd()
			if err != nil {
				ExitError("Cannot determine current directory: %v", err)
			}
			name = filepath.Base(cwd)
		}

		// Check if depotly.yaml already exists
		if utils.PathExists("depotly.yaml") {
			PrintWarn("depotly.yaml already exists in the current directory")
			if !utils.Confirm("Overwrite?") {
				PrintInfo("Init cancelled")
				return
			}
		}

		// Create directory structure
		dirs := []string{
			"db/migrations/postgres",
			"db/seeds/postgres",
			"db/schema/postgres",
			".depotly/runtime",
			".depotly/backups/postgres",
			".depotly/backups/mongo",
			".depotly/reports",
		}

		if err := utils.EnsureDirAll(".", dirs); err != nil {
			ExitError("Failed to create directories: %v", err)
		}

		// Generate default config
		cfg := config.DefaultConfig(name)

		if err := config.Save("depotly.yaml", cfg); err != nil {
			ExitError("Failed to write depotly.yaml: %v", err)
		}

		// Create empty schema placeholder
		schemaDir := "db/schema/postgres"
		schemaFile := filepath.Join(schemaDir, "latest.sql")
		if !utils.PathExists(schemaFile) {
			os.WriteFile(schemaFile, []byte("-- PostgreSQL schema for "+name+"\n-- Generated by depotly pg schema-dump\n\n"), 0644)
		}

		fmt.Println()
		PrintSuccess("Depotly project initialized: %s", name)
		fmt.Println()
		fmt.Println("  Config:    depotly.yaml")
		fmt.Println("  Migrations: db/migrations/postgres/")
		fmt.Println("  Backup:     .depotly/backups/")
		fmt.Println()
		fmt.Println("Next steps:")
		fmt.Println("  depotly doctor   # Check Docker and prerequisites")
		fmt.Println("  depotly up       # Start all services")
		fmt.Println("  depotly check    # Verify services are reachable")
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().StringVarP(&projectName, "name", "n", "", "Project name (default: current directory name)")
}
